# Check diagnostic text AND exact exit status, rather than accepting any failure.
if(CASE STREQUAL "missing_model")
    set(args nonexistent-model.obj)
    set(expected "cannot open model")
elseif(CASE STREQUAL "invalid_size")
    set(args --width 0)
    set(expected "dimensions must")
elseif(CASE STREQUAL "oversized_size")
    set(args --height 4097)
    set(expected "dimensions must")
elseif(CASE STREQUAL "bad_number")
    set(args --width 12junk)
    set(expected "dimensions must")
elseif(CASE STREQUAL "missing_value")
    set(args --output)
    set(expected "missing value")
elseif(CASE STREQUAL "unknown")
    set(args --unknown)
    set(expected "unexpected argument")
elseif(CASE STREQUAL "duplicate_model")
    set(args a.obj b.obj)
    set(expected "unexpected argument")
elseif(CASE STREQUAL "bad_camera")
    set(args --eye 0 0 0)
    set(expected "camera")
elseif(CASE STREQUAL "bad_light")
    set(args --light 0 0 0)
    set(expected "light direction")
elseif(CASE STREQUAL "missing_texture")
    set(args --texture nonexistent-texture.ppm)
    set(expected "cannot open texture")
elseif(CASE STREQUAL "output_failure")
    set(args --output . --width 8 --height 8)
    set(expected "cannot write output")
else()
    message(FATAL_ERROR "Unknown CLI test case")
endif()
execute_process(COMMAND "${PROGRAM}" ${args} RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE error)
if(NOT status STREQUAL "1" OR NOT error MATCHES "${expected}")
    message(FATAL_ERROR "Expected exit 1 and '${expected}'; got ${status}: ${out}${error}")
endif()
